name: Auto Update Rates

on:
  schedule:
    - cron: "*/5 * * * *"   # ҳар 5 дақиқа
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright requests
          playwright install --with-deps

      - name: Run scraper
        run: python scrape.py

      - name: Commit updated data.json
        run: |
          git config --global user.name "auto-bot"
          git config --global user.email "auto@bot.com"
          git add data.json
          git commit -m "Auto update $(date)" || echo "No changes"
          git push
